### ISSUE TITLE
Setting up AppVeyor for an org

### ISSUE THREAD

**Issue by jakirkham** [zarr-developers/zarr#226]
Unlike Travis CI or Coveralls, the AppVeyor setup for an org is a little different. Namely we need to have a dedicate org email, which could use the [GMail `+` trick]( https://gmail.googleblog.com/2008/03/2-hidden-ways-to-get-more-from-your.html ) or similar. Then users can be added via this administrator account. More details in this [doc]( https://www.appveyor.com/docs/team-setup/ ).

**Comment by jakirkham** [comment]
As this would be the same org account for `numcodes` as `zarr`, no need to open this issue again on that repo.

**Comment by alimanfoo** [comment]
Hi @jakirkham, I *think* AppVeyor should be set up, but I am seeing an issue with the webhook which means that builds are not getting triggered for PRs. It looks like the webhook POST for a "push" event is getting through fine, but the POST for "pull request" events is returning 403, with this in the message body:

```
{"message":"HTTP GET to https://api.github.com/repos/zarr-developers/zarr/pulls/227 returned status code 403: Forbidden\nFull response body:\n{\"message\":\"API rate limit exceeded for alimanfoo.\",\"documentation_url\":\"https://developer.github.com/v3/#rate-limiting\"}"}
```

Is this anything you've seen before? I googled around a bit but can't find an obvious solution.

**Comment by alimanfoo** [comment]
Scratch that, looks like AppVeyor has righted itself.

**Comment by jakirkham** [comment]
I have seen that issue before, but mostly in the context of `conda-forge` feedstocks where we actually do go over the GitHub rate limit sometimes and have taken measures to address that.

Can't see why you would have run into the issue here though. The GitHub rate limit resets every hour. So even if that issue does come up, it will eventually go away. The fact that it came up at all is what is interesting.

We should keep an eye on it and see if it reoccurs in the future.

**Comment by jakirkham** [comment]
AppVeyor setup LGTM. So closing this out.
