### ISSUE TITLE
Support for Subarrays

### ISSUE THREAD

**Issue by jonahjoughin** [zarr-developers/zarr#271]
First of all, I want to say thank you for all you’re work on this project. I spent quite a while looking for something like this to use in my work, and it’s been extremely helpful. 

Recently, I’ve been looking into support for parallel/distributed writes and reads, which has generally worked quite well up until this point. I’ve noticed, though, that this generally seems to be limited to operations on an entire array. It’s difficult to take advantage of parallelism when writing to only a subset of the array. If I’m not mistaken, this is largely due to the limitations of `__setitem__` and `__getitem__`. 

I wonder if this could be solved by adding support for subarrays as an extension of views or through a similar means. An array with the same underlying representation but different indexing could be created, and then used in methods like dask’s `to_zarr` and `store`. This could also be paired with the `extend` function previously proposed, enabling more efficient appending of data. I'd be interested to hear what you have to say about this.

**Comment by alimanfoo** [comment]
Hi @jonahjoughin, many apologies for not responding to this at the time, the notification got buried in an email backlog.

FWIW you can write to different regions of a zarr array in parallel. E.g., typically when you use dask's `to_zarr` or `store` then each chunk of the resulting computation will be stored into the array in parallel. Under the hood, each worker is calling `__setitem__` with data for a region of the array. 

If you are careful to align the chunk boundaries of your computation with the chunk boundaries of the array, then there is nothing special you need to do to avoid any conflicting writes, you can just fire away. Further details on when synchronisation is needed are in the tutorial section on [parallel computing](https://zarr.readthedocs.io/en/stable/tutorial.html#parallel-computing-and-synchronization).

Hth. If this doesn't completely answer your question or there's any other aspect you'd like to discuss, please feel free to reopen.
