### ISSUE TITLE
Race condition in storage.py for NestedDirectoryStore writes

### ISSUE THREAD

**Issue by jmswaney** [zarr-developers/zarr#272]
I've encountered a `FileExistsError` when writing in parallel to a `NestedDirectoryStore` that says:

`FileExistsError: [Errno 17] File exists: '/media/jswaney/Drive/Justin/coregistration/whole_brain_tde/fixed/zarr/4/10'`

The error points to the `os.makedirs(dir_path)` line in `__setitem__` for the `DirectoryStore` class:

```python
dir_path, file_name = os.path.split(file_path)
if os.path.isfile(dir_path):
    raise KeyError(key)
if not os.path.exists(dir_path):
    try:
        os.makedirs(dir_path)  # Error raised here
    except Exception:
        raise KeyError(key)
```

I was doing the chunk compression with 12 workers, so I think one of them created the subdirectory while another had already checked that it didn't exist. When it got to `os.makedirs`, it gave the expected error. A quick fix would just be to catch this error, but a better fix might be to just make all the directories for a `NestedDirectoryStore` ahead of time.

**Comment by alimanfoo** [comment]
Thanks Justin. On Python 3 I think we could just do os.makedirs(...,
exist_ok=True). Not available in Python 2 unfortunately.

There's also another race condition issue in DirectoryStore, would be good
to get both resolved, could be addressed in same PR:
https://github.com/zarr-developers/zarr/issues/263

**Comment by jmswaney** [comment]
It looks like there are a couple options for the Python 2 vs 3 problem listed [here](https://stackoverflow.com/questions/273192/how-can-i-safely-create-a-nested-directory-in-python?rq=1). They mention the `exist_ok=True` option in the context of the `pathlib` module which has been backported to Python 2 in the `pathlib2` module, but it might be weird to use this OO-style path handling just for this though. Another option is to catch the general `OSError` and just throw an error if the directory still doesn't exist.

**Comment by jakirkham** [comment]
It sounds like we are already interested in using `pathlib`. ( https://github.com/zarr-developers/zarr/issues/261 ) Maybe using the [`pathlib`-based solution]( https://stackoverflow.com/a/45547008 ) will work for us and we can add [`pathlib2`]( https://pypi.org/project/pathlib2/ ) as a requirement.

**Comment by jakirkham** [comment]
Note: Work on this is currently being pursued in PR ( https://github.com/zarr-developers/zarr/pull/318 ).
