### ISSUE TITLE
ValueError: group not found at path ''

### ISSUE THREAD

**Issue by NicWayand** [zarr-developers/zarr#304]
```python
fs = gcsfs.GCSFileSystem(project='sipn2-pangeo', token='browser', access='read_only')
gcsmap = gcsfs.mapping.GCSMap('sipn-sic', gcs=fs, create=False)

# Open Zarr dataset
ds_gcs = xr.open_zarr(gcsmap)

ds_gcs

```
Note this dataset cannot yet be made public.

#### Problem description

I have use the above commands to load this zarr dataset many times, today I get the below error. What "group" is the error message referring to? Also, I can load the local zarr dataset using xarray fine.

`ValueError: group not found at path ''`

#### Version and installation information

Please provide the following:

* Value of ``2.2.0``
* Value of ``0.5.5``
* Version of Python interpreter 3.6
* Operating system (Linux)
* How Zarr was installed ("using conda")

**Comment by martindurant** [comment]
Probably the path passed to the mapper should be `'/sipn-sic'` ?

**Comment by NicWayand** [comment]
thanks @martindurant, turns out it was missing some .zattrs files (uploaded ./* files instead of just the zarr dir)
