### ISSUE TITLE
Adding a Gitter channel

### ISSUE THREAD

**Issue by jakirkham** [zarr-developers/zarr#311]
Opening this based on discussion in issue ( https://github.com/zarr-developers/zarr/issues/291 ) to figure out if we want a Gitter channel (sounds like probably) and if so how we want it structured (e.g. one room, room per repo, dev and public rooms, etc.). Thoughts welcome.

**Comment by ryan-williams** [comment]
Just creating one for this repository, to start, sounds straightforward and would be great! Can split to more rooms later if necessary…

**Comment by jakirkham** [comment]
Per our discussion at today's meeting have set this up. Added PR ( https://github.com/zarr-developers/zarr/pull/413 ) to add a badge with a link to the README.
