### ISSUE TITLE
Creating a spec repo

### ISSUE THREAD

**Issue by jakirkham** [zarr-developers/zarr#312]
From discussion in issue ( https://github.com/zarr-developers/zarr/issues/291 ) and a few others, one idea is to have a repo with just the spec. Raising here to discuss further and then do (if we all consent).

**Comment by jakirkham** [comment]
Have created [a repo]( https://github.com/zarr-developers/spec ) per our previous discussions and suggestions from participants in today's call as a place for future discussions. Opening a few issues over there to get things started. Please feel free to raise more. Also the name is not set in stone in case there are better options. ( https://github.com/zarr-developers/spec/issues/1 )

**Comment by alimanfoo** [comment]
Hi @ryan-williams, sorry the call details were not published more widely, it was an ad hoc call pulled together by @rabernat to connect various people who had been on an email thread, but I think we'll probably schedule another call and if so will make sure it's open.

**Comment by jakirkham** [comment]
It would be great to have you @ryan-williams. As @alimanfoo said, this came together in an email thread responding to specific questions raised. However it would be good to have a regular call to discuss topics in the project generally. Perhaps we can discuss this in issue ( https://github.com/zarr-developers/zarr/issues/315 ).
