### ISSUE TITLE
open_consolidated doesn't accept enough kwargs

### ISSUE THREAD

**Issue by rabernat** [zarr-developers/zarr#336]
#### Minimal, reproducible code sample, a copy-pastable example if possible

`open_consolidated` doesn't accept the same keywords as `open_group`. This makes it hard to replace `open_group` with `open_consolidated` in downstream code (e.g. xarray).

```python
# create a new store
path = 'consolidated-test.zarr'
new_group = zarr.open_group(path, mode='w', synchronizer=None)
a = new_group.create('foo', shape=(10,))
zarr.consolidate_metadata(new_group.store)
group_cons = zarr.open_consolidated(path, mode='r', synchronizer=None)
```

gives the error
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-17-1eea689b4531> in <module>()
      3 a = new_group.create('foo', shape=(10,))
      4 zarr.consolidate_metadata(new_group.store)
----> 5 group_cons = zarr.open_consolidated(path, mode='r', synchronizer=None)

TypeError: open_consolidated() got an unexpected keyword argument 'synchronizer'
```

#### Problem description

The `open_consolidated` convenience function should pass through any arguments to the underlying `open` method. Instead, it does this

https://github.com/zarr-developers/zarr/blob/e44c4c5951181c86cc54998d4ddeb221f8059e72/zarr/convenience.py#L1181-L1185

Contrast this with `open`:

https://github.com/zarr-developers/zarr/blob/e44c4c5951181c86cc54998d4ddeb221f8059e72/zarr/convenience.py#L22-L36

#### Version and installation information

Zarr version is '2.2.1.dev97'

**Comment by alimanfoo** [comment]
Thanks @rabernat. Should be fine I think to add **kwargs to the signature for open_consolidated() and pass through to open().

**Comment by rabernat** [comment]
Just some discussion... I have been thinking about how to best integrate with xarray. I am wondering about the choice to add a new convenience method `open_consolidated` rather than add a `consolidated` keyword to the existing convenience method `open`. Do we really want to maintain two separate `open` functions?

I know I should have raised this question during the review, but it didn't occur to me until I started working on the xarray integration issue.

**Comment by alimanfoo** [comment]
FWIW I think I preferred a separate function because it kept the consolidated API separate for now, and so could be clearly marked as experimental. Also if you add in a ``consolidated`` argument to ``open()`` then you also need to add in another argument to allow user to specify the metadata key where the consolidated metadata is stored, which is obviously only relevant sometimes, so there's a bit more complexity to argument handling. These are minor points, I would be happy to revisit in future.
