### ISSUE TITLE
dask.distributed zarr reads slows down with additional workers

### ISSUE THREAD

**Issue by alpmdog** [zarr-developers/zarr#340]
#### Problem description

I have a zarr store with around 50 arrays on disk with a wide variety of dtypes. all stored with blosc compressor. While trying to parallelize some calculations with dask, I noticed that adding more workers to local dask cluster slows down the _decode_chunk calls.  In the documentation, there is some mention of blosc multithreading not working with multiprocessing and I tried setting BLOSC_NOBLOCK environment variable to see if makes a difference but didn't see any difference. Is this expected behavior with blosc? 

```
def test():
     zs = zarr.open('/tmp/zarr')
    for n,a in zs.arrays():
         a[:,:100].shape

delayed_res = []
for i in range(1000):
     delayed_res.append(dask.delayed(test))

dask,.compute(*dask_delayed)
```

Running this with a single worker each test call takes aroun 3.5 seconds, if I increase worker count to 10 than each call takes 4.5 seconds. 

#### Version and installation information

* zarr.__version__ : 2.2.0
* numcodecs.__version__: 0.5.5
* Python 3.6.6
* Linux
* zarr installed using conda

**Comment by alimanfoo** [comment]
Hi @alpmdog, how many cores on your system? I.e., what do you get from:

```python
import multiprocessing
multiprocessing.cpu_count()
```

**Comment by alpmdog** [comment]
72

**Comment by alimanfoo** [comment]
It's possible that with 10 workers, CPUs are being thrashed. If blosc is running with multiple threads, default is 8, and 8*10 > 72. However, the Blosc codec [tries to detect if it's being run in a child thread or process](https://github.com/zarr-developers/numcodecs/blob/master/numcodecs/blosc.pyx#L406) and if so disables use of multiple threads inside blosc. I have verified this works if using multiprocessing module directly, but not sure about dask distributed. If you want to forcibly disable blosc internal use of threads, you can do:

```
from numcodecs import blosc
blosc.use_threads = False
```

...which I think would need to get executed in each worker process somehow.

Alternatively you may be able to get the same effect via environment variables, but I think you'd need both:

```
BLOSC_NTHREADS=1
BLOSC_NOLOCK=1
```

Hth.

**Comment by alpmdog** [comment]
Thanks for the quick reply. Let me give this a try. Now that I am looking at top on the machine, it does look like CPUs are thrashed.

**Comment by alpmdog** [comment]
Needed to also set OMP_NUM_THREADS to 1 as well. Not sure why this was needed but once I did this, dask workers behaved as expected.

**Comment by jakirkham** [comment]
Likely one of your other dependencies uses OpenMP.

**Comment by alpmdog** [comment]
From my perspective, issue is resolved. Thanks for the quick response.

**Comment by jakirkham** [comment]
Thanks. Let us know if other issues crop up.
