### ISSUE TITLE
support for per-chunk compression

### ISSUE THREAD

**Issue by erhanbas** [zarr-developers/zarr#341]
Is it possible to have different compressors, e.g. lossy and lossless for individual chunks?

In a scenario, where you have a mask of importance, where you want to keep signal with lossless compression or even with no compression, but have other parts of the signal with lossy compression for efficiency and space.

For example we have:

> import zarr
A = zarr.zeros((32, 32), chunks=(4, 4))

important region that I want to keep is `A(4:11,4:11)`, where we want to go lossless, e.g. zlib, then for the rest I want to use quantize from numcodecs for lossy compression. This way, will have high precision for interesting parts within mask and have lossy compression for out of mask and have two different compressor for different parts of a single array at chunk level.

**Comment by alimanfoo** [comment]
Hi Erhan, thanks for getting in touch. That's not currently possible I'm
afraid, the compressor is configured for an entire array, so all chunks are
processed via the same encoding pipeline.

There is a possible workaround, where you create two arrays with the same
shape, one with lossy and the other with lossless compression. You then
choose which regions to put data in, based on your mask. Under the hood,
chunks only get materialised when written, so each array would have an
empty region with zero storage cost corresponding to the region containing
data in the other. Not sure this is a solution as you'd still need some
logic on your side to read data from the appropriate array based on the
mask, but thought I'd mention the idea.

**Comment by erhanbas** [comment]
Thanks, it is a good starting point for me.
