### ISSUE TITLE
Coveralls not reporting

### ISSUE THREAD

**Issue by jakirkham** [zarr-developers/zarr#358]
It appears Coveralls is no longer reporting coverage. Not totally sure why this is happening, but figured it deserved an issue to track and log further investigation.

**Comment by jakirkham** [comment]
Tried resyncing the Coveralls repo with GitHub, but that doesn't seem to have affected this.

**Comment by jakirkham** [comment]
Am trying to add the new Travis CI app to the `zarr-developers` org. This is needed as the old Travis CI integration is deprecated. Plus it may also solve this problem.

**Comment by jakirkham** [comment]
This seems to be working again. Closing.

**Comment by alimanfoo** [comment]
Thanks @jakirkham. Out of interest, did this get fixed by anything you did, or do you think it was just a transient thing?

**Comment by jakirkham** [comment]
Honestly I'm not sure. If it did, it seemed to take a while to have an effect. May just be Coveralls was being sluggish about processing requests. Something to keep an eye on in either case.
