### ISSUE TITLE
Add SQLite

### ISSUE THREAD

**Issue by jakirkham** [zarr-developers/zarr#365]
As another nice builtin Python option, it would be great to implement an SQLite-based key-value store. Most users are likely to have SQLite support in Python out-of-the-box. Not to mention [many languages support SQLite]( https://en.wikipedia.org/wiki/SQLite#Programming_language_support ), which should help in cases where the same data may need to be viewed in various languages. Finally in industry it is quite common for databases to support SQL to make using the database easier for people familiar with this language, which should help if we want to make other mutable mappings that leverage SQL in the future.

**Comment by jakirkham** [comment]
Some good info in [this doc]( https://www.sqlite.org/cvstrac/wiki?p=KeyValueDatabase ).

**Comment by jakirkham** [comment]
Have added an implementation in PR ( https://github.com/zarr-developers/zarr/pull/368 ).

**Comment by alimanfoo** [comment]
Just mentioning that, in googling around sqlite and key-value stores, I found there is something called [LSM](http://charlesleifer.com/blog/using-sqlite4-s-lsm-storage-engine-as-a-stand-alone-nosql-database-with-python/) which apparently is a new key-value store developed originally as a storage engine for sqlite4, but which can be used as a standalone package. So LSM could be another possible store implementation for zarr. Doesn't take away from the value of having the sqlite3 implementation in #368, it would be a different store class.

**Comment by jakirkham** [comment]
Very cool. Looks like SQLite4 is going to be a very nice improvement!

While the SQLite3 implementation has value on its own, am hopeful that demonstrating how to leverage SQL to implement this is handy for users working with or interested in other databases that support SQL and want to use Zarr with them.

**Comment by alimanfoo** [comment]
> Very cool. Looks like SQLite4 is going to be a very nice improvement!

FWIW I read somewhere that there are question marks about whether sqlite4 is going to happen, however the LSM package stands by itself and so could be used regardless of what happens with sqlite4.

> While the SQLite3 implementation has value on its own, am hopeful that demonstrating how to leverage SQL to implement this is handy for users working with or interested in other databases that support SQL and want to use Zarr with them.

That's a nice idea.

**Comment by jakirkham** [comment]
> FWIW I read somewhere that there are question marks about whether sqlite4 is going to happen...

Looks like you are right.

ref: https://sqlite.org/src4/info/c0b7f14c0976ed5e
