### ISSUE TITLE
Use stale bot?

### ISSUE THREAD

**Issue by alimanfoo** [zarr-developers/zarr#387]
I notice some repos are using a stale bot to close issues that have been inactive for a while. This can seem a bit brusque at first, but is probably a good way of keeping attention focused on issues for which there is recent activity and thus are probably still relevant.

(If we went ahead, also would add the stale bot for numcodecs.)

Any objections?

**Comment by jhamman** [comment]
I'd be 50/50 on this. On the upside, it's nice to keep a tidy issue/PR space. On the downside, closed issues aren't searched as much so we'd be likely to get more duplicate issues.

I was the one that setup the stale bot for the Pangeo project. I think it makes sense there because so many issues are open-ended and time limited (announcing an upcoming meeting for example).

**Comment by alimanfoo** [comment]
Thanks @jhamman. TBH I'm about 50/50 too, but thought it was worth discussing.

**Comment by jakirkham** [comment]
Personally I'm closer to -0.5 on this. While it does sound nice to tidy issues, the bot doesn't quite behave in the way one might expect.

For instance, it seems reasonable to close an issue where we are waiting for feedback for a long time and never get any. However it doesn't seem reasonable to close a user's issue when we were unresponsive for a while and the user was being respectful and not trying to add noise. The bot doesn't seem to know the difference and closes both of these.

Further it seems to incentivize (bad) behavior in the latter case. IOW users keep pinging a know issue to avoid the bot closing it. Alternatively it could discourage users that didn't get feedback from contributing in the future (if all that happened was the bot closed their issue). Though this latter case is pretty unlikely with Zarr specifically as we have generally been good about being responsive.

xref: https://github.com/probot/stale/issues/67
xref: https://github.com/conda-forge/conda-forge-enhancement-proposals/pull/9

**Comment by alimanfoo** [comment]
Thanks @jakirkham, totally see your points. I think I'll close this one, can always revisit in future if we feel differently.

**Comment by alimanfoo** [comment]
Perhaps we need a "reminder bot" instead :-) E.g., something that pings @zarr-developers/core-devs if no-one gives an initial response on an issue for more than a certain time, or if discussion does go cold for more than a certain time. But never actually closes issues.
