### ISSUE TITLE
Default efficient row iteration

### ISSUE THREAD

**Issue by jeromekelleher** [zarr-developers/zarr#398]
It seems like iterating over a chunked array is inefficient at the moment, presumably because we're repeatedly decompressing the chunks. For example, if I do
```python
    for pos, row in enumerate(data_root.variants):
        print(row)
        if pos == 1000:
            break
```
it takes several minutes (data_root.variants is a large 2D chunked matrix) but if I do
```python
    for pos, row in enumerate(chunk_iterator(data_root.variants)):
        print(row)
        if pos == 1000:
            break
```
it takes less than a second, where

```python
def chunk_iterator(array):
    """ 
    Utility to iterate over the rows in the specified array efficiently
    by accessing one chunk at a time.
    """
    chunk_size = array.chunks[0]
    for j in range(array.shape[0]):
        if j % chunk_size == 0:
            chunk = array[j: j + chunk_size][:]
        yield chunk[j % chunk_size]
```

To me, it's quite a surprising gotcha that zarr isn't doing this chunkwise decompression, and I think it would be good to do it by default. There is a small extra memory overhead, but I think that's probably OK, given the performance benefits.

Any thoughts?

**Comment by jakirkham** [comment]
It sounds like what you want is a cache for decoded chunks, which is proposed in PR ( https://github.com/zarr-developers/zarr/pull/306 ). If that sounds right, would you be ok closing this to keep discussion over there? If not, what else are you looking for?

**Comment by jeromekelleher** [comment]
Ah, that's a good feature, thanks @jakirkham! This is related, but I guess addresses a more limited application and is simpler. What I'm suggesting here is that ``__iter__`` methods use something like the ``chunk_iterator`` internally so that there's automatically good iteration performance even if you don't specify the LRU cache. Running a simple for-loop *should* have good performance by default, I think.

Any thoughts @alimanfoo?

**Comment by alimanfoo** [comment]
Hi @jeromekelleher, I like your suggestion. As @jakirkham says, the cache for decoded chunks would partly solve this, but as you say iteration is actually a simpler requirement where you only cache one chunk at a time while you iterate through it. PR welcome.

**Comment by jeromekelleher** [comment]
It looks like there aren't any tests for iteration currently. It belongs in ``test_core`` in principle, but really we just want to test this over a selection of arrays that have a bunch of different dimensions and chunk sizes.  Any pointers on where this should go @alimanfoo and where I can find some pre-defined arrays that would be suitable?

**Comment by alimanfoo** [comment]
I'd suggest adding a `test_iter()` method on the `TestArray` class in the `test_core` module. E.g., something like:

```python
    test_iter(self):
        params = (
            ((1000,), (100,)),
            ((100, 100), (10, 10)),
            # any other combination of shape and chunks you'd like to test
        )
        for shape, chunks in params:
            z = self.create_array(shape=shape, chunks=chunks, dtype=int)
            a = np.arange(np.product(shape)).reshape(shape)
            z[:] = a
            for expect, actual in izip_longest(a, z):
                assert_array_equal(expect, actual)
```
