### ISSUE TITLE
Zarr datasets fail to deserialize when returned by dask

### ISSUE THREAD

**Issue by jonmjoyce** [zarr-developers/zarr#416]
```python
import xarray
from distributed import Client

def simplezarr():
    ds = xarray.open_zarr('/my/zarr/path')   
    return ds 

client = Client( 'http://my.dask.host' ) 
future = client.submit(simplezarr)
future.result()
```

#### Problem description

I get an error whenever I try to deserialize a zarr object. I am running computations on a remote dask cluster and attempting to return the result to my local machine. This works when I use xarray to load regular GRIB files, but it does not work if I load zarr files and run the same code.

I am not sure if it is an xarray or zarr problem, but the error is thrown from zarr:

distributed.protocol.pickle - INFO - Failed to deserialize b'[lots of serialized data]'
Traceback (most recent call last):
  File "/home/jonmjoyce/miniconda3/envs/py36/lib/python3.6/site-packages/zarr/hierarchy.py", line 112, in __init__
    meta_bytes = store[mkey]
  File "/home/jonmjoyce/miniconda3/envs/py36/lib/python3.6/site-packages/zarr/storage.py", line 738, in __getitem__
    raise KeyError(key)
KeyError: '.zgroup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jonmjoyce/miniconda3/envs/py36/lib/python3.6/site-packages/distributed/protocol/pickle.py", line 59, in loads
    return pickle.loads(x)
  File "/home/jonmjoyce/miniconda3/envs/py36/lib/python3.6/site-packages/zarr/hierarchy.py", line 273, in __setstate__
    self.__init__(*state)
  File "/home/jonmjoyce/miniconda3/envs/py36/lib/python3.6/site-packages/zarr/hierarchy.py", line 114, in __init__
    err_group_not_found(path)
  File "/home/jonmjoyce/miniconda3/envs/py36/lib/python3.6/site-packages/zarr/errors.py", line 29, in err_group_not_found
    raise ValueError('group not found at path %r' % path)
ValueError: group not found at path ''
distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "/home/jonmjoyce/miniconda3/envs/py36/lib/python3.6/site-packages/zarr/hierarchy.py", line 112, in __init__
    meta_bytes = store[mkey]
  File "/home/jonmjoyce/miniconda3/envs/py36/lib/python3.6/site-packages/zarr/storage.py", line 738, in __getitem__
    raise KeyError(key)
KeyError: '.zgroup'

#### Version and installation information

Please provide the following:

* zarr 2.2.0
* Value of ``numcodecs.__version__`` (not sure)
* Python 3.6.6
* Local machine: Linux VM running Eclipse/PyDev. Remote host: Linux (Docker image)
* Conda in Docker image

**Comment by martindurant** [comment]
It is unusual to try to serialise the xarray object in this way, since it already contains dask objects - you normally operate on it using xarray methods, and dask will figure out the computations to perform on the cluster. What are you trying to achieve?

If you really do want to serialise xarray objects, you may be interested in https://github.com/intake/intake-xarray/blob/master/intake_xarray/xarray_container.py#L26 and later in the module, which essentially packs up the metadata only into a serialisable dict that zarr understands, but you need to fill in the dask tasks with where the data will actually come from. I think it's unlikely this is what you were after.

**Comment by jonmjoyce** [comment]
Thank you for the reply. Perhaps you can tell me if I'm using dask incorrectly.

I have a remote data store which is accessible by the dask cluster. I have written Python code locally which submits "jobs" to the remote server using client.submit(). The jobs themselves are pretty simple: open 10 files, take the mean of one of the fields (a 2D array), and return it. 

Specifically for one of the tests, I am loading the files in parallel and returning just the field I want to analyze. Then I submit a second job to take the mean of that data. If I could persist those fields in memory instead of returning them that would be a great alternative but I have not had success with the xarray DataArray.persist() method. Perhaps I am incorrectly understanding how these tools work this being my first project using them.

Is it uncommon to program locally and submit jobs? Even when I was working in a Jupyter notebook hosted on the same cluster I found I had to use the dask submit method in order for the entire cluster to get utilized in parallel, but it seems like most of the dask documentation looks like they run it directly on the cluster itself somehow.

**Comment by martindurant** [comment]
Still, you don't want to make this xarray object, which has references to data that can only be seen from the worker, pass it to the client and expect it to be able to do something with it.

In this case you probably want to use `worker_client` for this kind of thing. Something like
```
from dask.distributed import worker_client

import xarray
from distributed import Client

def simplezarr():
    with worker_client():
        ds = xarray.open_zarr('/my/zarr/path')
        ds.do_something.maybe_output
        return "Done" 

client = Client( 'http://my.dask.host' ) 
future = client.submit(simplezarr)
future.result()
```

**Comment by jonmjoyce** [comment]
Thank you for pointing out that feature; I didn't know it existed! I rewrote my test to use worker_client and it is functioning as desired. You may close this issue if you'd like as I agree now that returning a zarr is an uncommon use-case.
