### ISSUE TITLE
Make azure-storage-blob an optional test requirement

### ISSUE THREAD

**Issue by jakirkham** [zarr-developers/zarr#419]
Currently `azure-storage-blob` is required for testing. Meaning that if it is not installed the tests cannot be run. It would be nice if `azure-storage-blob` was an optional test requirement. This way we could simply skip the tests that require `azure-storage-blob` and run the rest of the tests. For more details about the issue, please see [this build log]( https://ci.appveyor.com/project/conda-forge/zarr-feedstock/builds/23296537/job/t5wcfka88ohwo72p ).

**Comment by jakirkham** [comment]
Another reason this is a good idea is testing `azure-storage-blob` requires Azurite. While this is fine to use in CI or perhaps for a developer working on the Azure storage back end, it is not an easy ask in many other situations (e.g. packaging). So relaxing this requirement will help ensure the basic tests can still be run even when this requirement is not met.

**Comment by rabernat** [comment]
I agree with making the azure libs an optional test requirement. As long as we have these test run in travis somewhere, that's enough.

On a practical note, I'm really hoping to install zarr 2.3 via conda forge. It sounds like that won't be happening. Is the idea to cut 2.3.1 asap it get around this conda forge test issue?

**Comment by jakirkham** [comment]
Thanks for the review @rabernat. Yep the tests are still running on both CIs. Agree we should continue to do so.

Yes the idea is to do a quick hot-fix with just this change. Should have time to do it Monday if this is agreeable. Once we tag the release am planning on getting it in PyPI and conda-forge.
