### ISSUE TITLE
Updating Readthedocs integration

### ISSUE THREAD

**Issue by jakirkham** [zarr-developers/zarr#423]
As [GitHub Services was deprecated]( https://developer.github.com/changes/2018-04-25-github-services-deprecation ), it appears that Readthedocs stopped building both for Zarr and Numcodecs. Have written up this issue to note this problem and the fact these need to switch to GitHub Webhooks.

**Comment by jakirkham** [comment]
Have installed GitHub Webhooks for both repos and triggered builds for all recent versions of Zarr and Numcodecs. All appears to be in working order now. So this is completed.

**Comment by alimanfoo** [comment]
Thanks @jakirkham.
