### ISSUE TITLE
What's an intelligent way of loading a compressed array completely from disk into memory - also (identically) compressed?

### ISSUE THREAD

**Issue by s-m-e** [zarr-developers/zarr#428]
I posted [this question](https://stackoverflow.com/q/55443505/1672565) on stackoverflow a little more than a week ago without receiving and answer - so I though I post it here in addition.

**Comment by jakirkham** [comment]
Thanks for the ping. Looks like there are now a couple answers. Hope that helps.

**Comment by s-m-e** [comment]
Has there been a "clean" method for this been added to `zarr` in the meantime? Those two answers provided suggestions for what can only be described as rather fragile approaches ...

**Comment by jakirkham** [comment]
Also the underlying `MutableMapping` should have a `clear` method that would purge it
