### ISSUE TITLE
Release 2.3.2?

### ISSUE THREAD

**Issue by jakirkham** [zarr-developers/zarr#433]
Would it be alright to cut a patch release? Thoughts @zarr-developers/core-devs?

**Comment by alimanfoo** [comment]
No objections here. Looks like there isn't an entry in release notes for the changes in #427.

**Comment by jakirkham** [comment]
@QuLogic, would you have time to submit a PR for the changelog entry? If not, I can give it a look later.

**Comment by jakirkham** [comment]
Given this is just a minor test change, I'd rather not hold up the release.

**Comment by shikharsg** [comment]
Any chance of getting https://github.com/zarr-developers/zarr/pull/306 into the 2.3.2 release? In which case I will document it in `docs/release.rst`.
Or is this something that is more appropriate when we do a 2.4 release?

**Comment by jakirkham** [comment]
As it is adding new functionality, it should be targeting 2.4. Though I agree it would be exciting to get that integrated. 🙂

**Comment by jakirkham** [comment]
> Looks like there isn't an entry in release notes for the changes in #427.

Doing this in PR ( https://github.com/zarr-developers/zarr/pull/441 ).

**Comment by jakirkham** [comment]
Have completed the release. Packages on PyPI and conda-forge. Sorry for the delays.

**Comment by alimanfoo** [comment]
Thanks a lot John :+1:
