### ISSUE TITLE
(Just a question)How to do something similar to numpy.where in Zarr?

### ISSUE THREAD

**Issue by manolinux** [zarr-developers/zarr#446]
Hi, all!

How can achieve something like:

selection =  np.where(dateSeries == today)

where dateSeries is a Zarr array. Or how can I dump a zarr array to NumPy, is there any underlying attribute that holds the values or maybe an iterator, as data maybe chunked? I think it's easy to store NumPy values into Zarr, but the recovery process into NumP seems to me a little bit obscure ... 

Kind regards, and thank you for your great software!
Manuel.

**Comment by alimanfoo** [comment]
Hi @manolinux, 

For computing over Zarr arrays, I use [Dask](https://docs.dask.org/en/latest/array.html). E.g.:

```python
import dask.array as da
xz = ...  # obtain a zarr array somehow
xd = da.from_array(xz, chunks=xz.chunks)
selection = da.where(xd == today).compute()
```

If you ever want to manually load data from a Zarr array into a Numpy array, use slicing, e.g.:

```
x = xz[:]  # load entire array into numpy array
x = xz[:10]  # load first 10 elements into numpy array
```

Hth.

**Comment by manolinux** [comment]
Thanks a lot, @alimanfoo !

Yes, i was thinking of something like that, also needed performing some statistics over the arrays, so Dask offers that power ...

**Comment by rabernat** [comment]
You can also use zarr with xarray, which is convenient for indexing. (The time based lookup you mentioned above is very easy with xarray.) 

http://xarray.pydata.org/en/stable/io.html
